### ISSUE TITLE
shadows are not loaded correctly back into UI from awd with shadows applied

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#101]
**Steps to reproduce**
- open onkba/onkba_light.awd
- goto lights -> DirectionalLight 1
- goto materials -> Material 2

**Expected results**

light should have castShadows = true and added SoftShadowMethod1
material should have shadow light selected to DirectionalLight 1 and Shadow method selected to SoftShadowMethod1

**Comment by 80prozent** [comment]
Light.castShadow not set to true was a bug on my side (together with ShadowMapper not parsed correctly).
