### ISSUE TITLE
Diffuse gradient doesn't update when a new texture is selected

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#119]
**Steps to reproduce**
- open MonsterHead_lights.awd
- go into the material => shading panel
- from the diffuse method dropdown select "Gradient diffuse method"
- go into the Gradient diffuse method properties panel
- from the texture dropdown for "gradient" select "new texture"  and select a new texture to load

**Expected result**

gradient texture applied to the material in the view should update with the new texture

**Actual result**

gradient texture applied to the material in the view doesn't change

**Comment by rob-bateman** [comment]
this still doesn't apply in the view or dropdown menu when initially loading a new texture

**Comment by rob-bateman** [comment]
it also appears that the gradient texture is being applied to the texture property of the method, rather than the gradient property. can you please confirm?

**Comment by rob-bateman** [comment]
the application of the gadientdiffuse texture now appears to happen correctly, but when you try to save the file and reload, the gradient property resets to the default texture:

**Steps to reproduce (from original steps)**
- save the file
- reload the file

**Expected result**

monsterhead to load back with the new texture applied for the gradientdiffusemethod

**Actual result**

monsterhead loads back in with the default texture applied in the gradientdiffusemethod

**Comment by 80prozent** [comment]
fixed in 9f8db9a
