### ISSUE TITLE
Focus interaction for scene objects

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#13]
The focus interaction moves the focus and distance of the camera so that it cetrally displays the selected object at a suitable distance for the size of the object.

This can work on any object container or group of (selected) objects, and on the root object container (ie the scene)

when a file is initially loaded, the focus interaction will be called on the scene so that the file contents are displayed centrally and at a suitable size

**Comment by qornflex** [comment]
Normally, all is ready for this feature in my last push
