### ISSUE TITLE
Copy Texture-Files to output-folder when exporting AWD with external Textures

### ISSUE THREAD

**Issue by 80prozent** [awaytools/AwayBuilder#135]
Atm there is no way to extract a embed Texture from a AWD-File.

I think AwayBuilder should have a option to save Textures as Texture-files (jpg/png).

For the AWDEncoder, i would like to include a option to create all needed textures in the output-folder (if they do not allready exists).

**Comment by 80prozent** [comment]
This is implemented for the Desktop-Version.
I think it should kept open until its implemented in the web-version too.

**Comment by keyemkey** [comment]
exporting external Textures disabled
