### ISSUE TITLE
loading level.awd now throws a runtime error with the parser

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#140]
**Steps to reproduce**
- open level.awd

**Comment by 80prozent** [comment]
Very strange. This is a AWD2.0 File, that has its geometry-storage-precision set to use float64, when in fact it has float32 values stored. All AWD2.0 files should have all Storage-Precision set to use float32. 

Fixed in AWD2Parser by ignoring the Storage-Precision for all AWD2.0 files.
