### ISSUE TITLE
zOffset on objects has no effect on z-order, needs inclusion in depthrenderer codebase

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#15]
With any Widget, the object needs to be always rendered over the top of the object it is controlling, regardless of depth. For this, an update to the depthrender needs to take account of the zOffset property on entity objects, so that this depth value is added and depth order can be controlled

**Comment by Greg209** [comment]
FIxed with ab8f9b7dddb8b5ba776c3b40eab29c0d2f3c127a via layering the view (using the new layeredView property & clearing the depth buffer) rather than use of the zOffset property.
