### ISSUE TITLE
loading the orge md2 file does not display the material

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#158]
**Steps to reproduce**
- open a new library file
- import the md2 orge
- select the mesh
- look at the assigned material

**Expected result**

the material is the one for the imported texture at load time

**Actual result**

the material is the default material, despite the material texture displaying on the mesh. Also, when browsing to the material library panel, no material is present

**Comment by 80prozent** [comment]
This seams like a bug in the md2parser. 
It looks like the MATERIAL_COMPLETE Event is fired after the RESSOURCE_COMPLETE (cause the md2 start to load its dependencys after it has been completly parsed)
This far i could not find a quick fix for this.

**Comment by 80prozent** [comment]
md2 now fires Events like the rest of the Parsers.
