### ISSUE TITLE
Mouse events are not firing on the second view when sharing a context

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#16]
3D Mouse events from the orientation cube are not firing due to an incompatibility with the mouseeventmanager and multiple views.

**Comment by rob-bateman** [comment]
actually its just occurred to me that this could be because the view objects aren't being added in the correct order - in view3d, an invisible layer in the displaylist is used to capture initial 2d mouse events. If the orientation cube view is added to the displaylist underneath the main view, this could be what is stopping events from reaching this view instance

**Comment by Greg209** [comment]
That's true. The displaylist 'hit' object of one view is blocking the 'hit' object of the second view. Although re-arranging the order may help, there will still be transparent areas around the cube where events will be blocked from the lower main view. A potential solution may be to share a common 'hit' displaylist object that is used when the context is shared. I've taken a quick look but will need to look further into it.
