### ISSUE TITLE
bounding box for a mesh with children displays incorrectly

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#163]
**steps to reproduce**
- open new library
- create a new sphere geometry
- create a new mesh
- create a second mesh and drag to one side
- drag the second mesh over the first to parent it in the library panel
- click on the first mesh in the view

**expected result**

The selected mesh displays a container-style bounding box (with broken lines) around both meshes

**actual result**

The selected mesh displays a mesh-style bounding box around only itself, ignoring its child mesh

**Comment by Greg209** [comment]
Requires latest Away3d engine as well
