### ISSUE TITLE
Include Normal Data default on

### ISSUE THREAD

**Issue by JohnBrookes** [awaytools/AwayBuilder#172]
Just tested a file and got flat shading after export.
Realised theres an option "Include Normal Data"

If the AwayBuilder view is using normal data then this should be on. Or at least default on.

**Comment by 80prozent** [comment]
Hi john 
I will set the default for the normals to true. I think having this option to depent on the awaybuilder scengraph might get messy. Sometimes you want to explizit exlude normals  from export. If the option woukd change automaticcly when importing a file, it might be confusing.....

**Comment by 80prozent** [comment]
I have been thinking about this again.
It might be best, only to export normalData, if the "includeNormals"=true and if the "autoDeriveNormalData" of a Subgeometry is "false". 
This way we do not end up exporting unnecessary normalData.
To make this happen, we would need to add the "autoDeriveNormalData" to the SubGeometryVO. (SubGeometryVO.autoDeriveNormalData)
I think it would make sense to do this for normals and for tangents.

**Comment by 80prozent** [comment]
I added the autoDeriveNormals and autoDerivetangents to the SubGeometryVO.
Changed default for "includeNormals" and "includeTangents" to true, but only export them if they are not autoderived.
