### ISSUE TITLE
Cant select mesh children of objectContainer in viewport.

### ISSUE THREAD

**Issue by JohnBrookes** [awaytools/AwayBuilder#173]
eg if I have a main Group (Car) with child body parts. I cant select any body parts in the viewport. It will always select the main group.

Personal opinion but containers should only be selectable through the sceneObjects menu and not the viewport.

**Comment by Greg209** [comment]
Hi John,

For containers in the viewport you can double-click on container and it will 'open' up to allow object and container selections within it.

There is also a breadcrumb at the bottom indicating the level of child container you are currently at. Double clicking on the background of the viewport will raise the level of container selection.

**Comment by JohnBrookes** [comment]
Ahh so it does :)
Thanks shall close this.
