### ISSUE TITLE
AwayBuilder cannot be closed, if "save as" (on closing) is canceled

### ISSUE THREAD

**Issue by 80prozent** [awaytools/AwayBuilder#185]
**Steps to reproduce:**
- open any file in AwayBuilder
- change something in the scene 
- close AwayBuilder (use the menu->exit, or the close-button of the window)
- a pop up appears ("save" / "Dont Save" / "cancel") - choose "save"
- the "save as"-dialog appears 
- cancel the "save as"-dialog 
- try closing AwayBuilder again

**exspected result:**
- the pop up appears ("save" / "Dont Save" / "cancel")

**actual result**
- nothing happens

**Comment by keyemkey** [comment]
fixed
