### ISSUE TITLE
Deleting scene objects accidentally

### ISSUE THREAD

**Issue by kreys** [awaytools/AwayBuilder#188]
Repro steps:
1) Add some object to the scene (e.g. a camera)
2) Select this object
3) Switch to geometries tab
4) Create new geometry
5) Select this new geometry
6) Press delete - geometry is deleted and scene object as well

It seems to remember the selection for each group (geometries, materials, sceneObjects etc.) and then deletes all of them.

AwayBuilder 0.9.8 Beta

**Comment by keyemkey** [comment]
Fixed
