### ISSUE TITLE
Cut/Copy/Paste keyboard shortcuts on text inputs

### ISSUE THREAD

**Issue by kreys** [awaytools/AwayBuilder#190]
While editing text inputs (objects names, extra parameters), copy/paste shortcuts should affect the text - for now you are pasting last selected scene object into scene.

Mouse (combo box) copy/paste at text inputs works well.

**Comment by keyemkey** [comment]
related to https://issues.apache.org/jira/browse/FLEX-26025, workaround: spaces was added to native shortcats
