### ISSUE TITLE
ColorMaterial

### ISSUE THREAD

**Issue by kreys** [awaytools/AwayBuilder#191]
When you set a material for a mesh, and set all the textures to null and set some diffuse color, shouldn't it be parsed as ColorMaterial instead of TextureMaterial? When loading such file with away3d, it's loaded as TextureMaterial, which I suppose is not correct.

**Comment by 80prozent** [comment]
Hi
I think this is allready fixed on git. 
I just tried with the latest git, and it works as supposed (Material with no textures is exported as a ColorMaterial).

**Comment by kreys** [comment]
Thanks, it's really nice to hear that - my mistake that I didn't checked that twice, it surely wasn't working few days ago.
