### ISSUE TITLE
DAE import: "Animation root node null not found!" error.

### ISSUE THREAD

**Issue by alkabano** [awaytools/AwayBuilder#193]
**Steps to reproduce:**
1. Open AwayBuilder 0.9.8
2. Import [mario_testrun.dae](https://github.com/away3d/away3d-examples-fp10/blob/master/src/assets/mario_testrun.dae)
3. Animations -> SkeletonAnimationSet -> Animators -> Add new -> SkeletonAnimator1
4. Select SkeletonAnimator1 (left frame) and click on the first item in the Animations section (right frame).
5. Get "Animation root node null not found!" error.

[Screenshot](https://f.cloud.github.com/assets/4783311/696185/9a027178-dce0-11e2-80fd-70d3819c833c.png).

**Comment by keyemkey** [comment]
fixed
