### ISSUE TITLE
[Invalid report] ColorMaterial doesn't work

### ISSUE THREAD

**Issue by Jeronimoo** [awaytools/AwayBuilder#197]
<b>EDIT: My bad, this is related to <a href="https://github.com/awaytools/AwayBuilder/issues/191">this closed issue</a> which apparently was fixed on June 24th. The dev build I was using is from June 20th, so this bug report can probably be deleted.</b>

Hi,

Possibly a quick to fix bug here.

I am using dev build. When I use plain color instead of a texture on an AwayBuilder Mesh, the resulting AWD file displays the mesh with the default checker-board texture, ignoring the color.

Steps to reproduce:
- Create geometry
- Create material
- Within the material's "Colors&Textures" panel, set the diffuse texture to null so that the diffuse color picker is enabled
- Pick a diffuse color
- Create a mesh
- Apply previously created geometry and material to that mesh
- Save as AWD file
- Load the file either in an Away3D project or in AwayBuilder itself
- Watch how the default material is used
- Also notice that the material you created is not even present in the Materials panel

**Comment by 80prozent** [comment]
yes you are right...this is allready fixed
but i think the fix was in AwayBuilder, not the Away3d Engine....

**Comment by Jeronimoo** [comment]
I didn't look into the actual code, but the way I get it from this bug's behaviour, the issue is that the ColorMaterial was not saved into the exported AWD file at all.

If that's indeed the case, then Away3D itself wouldn't need to be fixed, only AwayBuilder :)
