### ISSUE TITLE
cannot current drag & drop items in left-hand library panel to lists in right-hand properties panel

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#206]
**Steps to reproduce**
- open blank library
- create a new pointlight
- create a new light picker
- try and drag and drop the pointlight into the lights list in the light picker properties panel

this behaviour will also stop users from drag / dropping animation nodes into an animation set properties panel, and material effects into a material properties panel

**Comment by keyemkey** [comment]
fixed
