### ISSUE TITLE
Cannot reopen a saved file

### ISSUE THREAD

**Issue by ThomasWeiss** [awaytools/AwayBuilder#221]
I’ve spent some time preparing a model using AwayBuilder and just found out that I cannot reopen it. It throws an “error #2030” and the UI gets… funky!

More details and the file can be found in this forum post: http://away3d.com/forum/viewthread/4817/

**Comment by 80prozent** [comment]
This has been fixed in the Away3d engine by this commit: 
https://github.com/away3d/away3d-core-fp11/commit/0cd9f7230b67a272db869a1819b84f8f638d4b0e
