### ISSUE TITLE
Unable to import model with 2 UV channels

### ISSUE THREAD

**Issue by 62316e** [awaytools/AwayBuilder#231]
Hi,

I need to have lightmap in my scene.
UV1: Baked lighting
UV2: Diffuse, Normal etc

I've tried exporting into
-OpenCollada
-Autodesk Collada 
-AWD (exporter on google code)
-3DS
Nothing works, second UV just ignored by LightMap method.

**Comment by 62316e** [comment]
!

**Comment by 80prozent** [comment]
Should be fixed with this commit:
https://github.com/awaytools/AwayBuilder/commit/224d33b10d9669124e634ce08012f444ce0afaf1
