### ISSUE TITLE
EnvMapMethod Crashes AwayBuilder when Reloading Scene

### ISSUE THREAD

**Issue by Rythameen** [awaytools/AwayBuilder#235]
I have imported a model into AwayBuilder, whenever I add an EnvMapMethod to a material, and then add a new Cube Texture, after I save the file, it works fine in my project but when I try reopen the awd file in AwayBuilder, it crashes with an Error #1009. Not sure if it makes a difference but I am using a Mac.

**Comment by 80prozent** [comment]
Should be fixed by this commit:
https://github.com/awaytools/AwayBuilder/commit/224d33b10d9669124e634ce08012f444ce0afaf1
