### ISSUE TITLE
AWDEncoder: Special characters and writeUTFBytes misconception

### ISSUE THREAD

**Issue by rdoi** [awaytools/AwayBuilder#236]
A couple of days ago, I've reported in the Away GIT that there was something wrong with the AWD2Parser.
It basically gives an error if you try to restore an AwayBuilder AWD that have a special character in the "extra" data somewhere.
https://github.com/away3d/away3d-core-fp11/issues/660

Well, I discovered that the problem is wider and not in the parser, but in the AWDEncoder itself.

It is based in a misconception about the ByteArray.writeUTFBytes and String.length.

It comes that in UTF8 it mixes 8bits and 16bits characters, so the string length (number of characters) is different than the number of bytes it uses.

  var str:String= "seleção";
  trace(str.length); // returns 7

  var ba:ByteArray= new ByteArray()
  ba.writeUTFBytes(str);
  trace(ba.length); // returns 9  

The 2 bytes difference is exactly those special characters which uses 16bits.

Knowing that and checking the AWDEncoder code, we can see everywhere things like:

1312: _blockBody.writeUnsignedInt(texturePath.length);
1313: _blockBody.writeUTFBytes(texturePath);     

That is obviously wrong, because its saving the number of characters not the effective bytes been written.

**Comment by 80prozent** [comment]
Hey rotoi
Thanks for the info.
What you say is correct and makes sense.
I fixed it for all strings that are written into the awd.
fix is commited to git, but you have to compile AB yourself, or wait for the next AB release version to use it.

just tried and could save and reopen a extra-property with name "test123äöü/?ß=&%$*#+~}][{"
