### ISSUE TITLE
LZMA bug

### ISSUE THREAD

**Issue by bboltz** [awaytools/AwayBuilder#238]
Hello,

I’m testing some things with the Away Builder Live Tool, and when I save a model with LZMA compression enabled,  it doesn’t save out the 4-byte uncompressed size at the beginning of the LZMA buffer.

This is different from the Away3D SDK C++, which does save out the 4-byte uncompressed size. 

Also, when I use the SDK to write a LZMA compressed file, and try to open it into the Away Builder Live Tool, I get an Error #1000, which locks up my browser.

Thanks

**Comment by 80prozent** [comment]
This is acctual a AWD-SDK issue.
I close the Issue here, and opened a new one in the AWD-SDK git.
https://github.com/awaytools/awd-sdk/issues/6
