### ISSUE TITLE
AWDEncoder: Not saving parent-id of containers

### ISSUE THREAD

**Issue by rdoi** [awaytools/AwayBuilder#240]
The current (master) encoder code is not saving the parentid of container objects in awd.

In AWDEncoder._encodeContainer3D lines 725 (master), there is a re-declaration of parentId paramenter, so the parentId will be always written as 0.

```
  private function _encodeContainer3D(container : ContainerVO, parentId:uint=0) : uint
        {           
            var i : uint;
            var parentId : uint; // <-- *** Why this is here? ***
            var returnID:uint=_encodeBlockHeader(22);
            _blockBody.writeUnsignedInt(parentId);
```

For some reason, the compiled version of AwayBuilder 1.0.0 works correctly...

**Comment by 80prozent** [comment]
hey rdoi
Yes, you are right, the `var parentId : uint;` should not be there.
But than again it really doesnt make any difference, as it is only declaring the var, not assigning a value. 
so the parentId from the function-parameters does not get overwritten.
 `var parentId : uint = 0;` would be bug. the present one is only not clean :)

I did pushed some small updates, that havnt been included in the compiled version yet...

**Comment by 80prozent** [comment]
I leave this issue open, to remind me to delete the `var parentId:uint;`

**Comment by rdoi** [comment]
You are right, the line as it is, is ignored and makes no difference. 
(We find out the workaround we added elsewhere (not related) was our problem.)
Anyway, the "var i:uint" is useless too..

Thanks for your time.
