### ISSUE TITLE
Zoom controls to be wired up to zoom on 3D view

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#3]
Zoom slider and buttons should update and be influenced by zoom in 3D view

**Comment by rob-bateman** [comment]
Another aspect of the zoom control that would be worth exploring is if a logarithmic zoom would work better for smoother movement at all zoom levels. Right now with the wheel, if you are zoomed in vary close to an object (or just ahve a very small object), the zoom step appears very large, while at far away zooms, the step is comparatively small. A logarithmic approach to zoom values would create the same amount of movement at all levels

**Comment by qornflex** [comment]
It is fixed now also according the FocusTarget feature.
Zoom steps are updated when you do a "focus" on the selected object

**Comment by rob-bateman** [comment]
Zoom steps in the zoom slider should be between 0 and 1. This represents the log(base 2) of distance, and should be what both the zoom controller and mousewheel use to control the distance value.

eg 

zoom = 0 => distance = log2(0) = -Infinity
zoom = 1 => distance  = log2(1) = 0

with this equation calculating distance, you should get an equivalent amount of motion at every level of zoom, proportional to the total level of zoom

in flash you cannot calculate log base 2 directly, so you need to use the following

function log2(x:Number):Number
{
    return Math.log(x)/Math.LN2
}

**Comment by rob-bateman** [comment]
fixed in 1c4b06c508b8b3e06aeb37884a292533315edacd
