### ISSUE TITLE
Small models move in 'steps' with position gizmo

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#34]
When trying to move very small objects on stage (ie when zoomed in) with the position gizmo, the position exhibits a quantisation, moving in steps rather than smoothly. Same problem can be seen when scaling with the scale gizmo

**Comment by Greg209** [comment]
With commit ab8f9b7dddb8b5ba776c3b40eab29c0d2f3c127a the gizmo translation and scaling is improved when zooming in but I still feel it needs improvement.

**Comment by rob-bateman** [comment]
fixed in a39438cc93848e497a0d189cce55f73df1b77ef1
