### ISSUE TITLE
horizontal wireframes disappear

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#37]
when viewing the orientation grid or the bounding box of a mesh, any horizontal lines rendered by the wireframe disappear. This is especially noticeable when the app in initially started. Presumably a problem in the wireframe renderer?

**Comment by Greg209** [comment]
Update made to the Away3D engine to fix this problem away3d/away3d-core-fp11@871401c8920a828325157dabce44f55c32954767
