### ISSUE TITLE
Pan control mode to move the center focus of hovercontroller

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#4]
The current motion is simply to turn the camera left and right, which doesn't sit well with switching back and forth between pan mode and rotate mode for the view

Desired functionality should be rotate of hovercontroller on click and drag for rotate mode (as is currently), and movement of target position of hovercontroller left/right/up/down for pan mode

**Comment by qornflex** [comment]
This is fixed now.
By default, camera is rotating when you click and drag.
If you press middleMouseButton or holding ALT key, you can pan.

To focus a mesh in target mode, for now, you can press Shift+F  if there is a mesh selected.
We need to have a button on the UI to call that function too.
The function is Scene3DManager.focusTarget()
