### ISSUE TITLE
Deleting doesn't work on mesh with children

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#40]
**Steps to reproduce:**

open onkba/onkba.awd

click on Bip01 in the library panel

click the delete button

**Expected result**

entire Bip01should disappear in the library and the view

**Actual result**

Bip01 stays exactly the same, or some (but not all) of the tree disappears. In the latter case, tree is unusable after this point

**Comment by rob-bateman** [comment]
This also doesn't seem to work when selecting any mesh in the library panel. eg:

open sponza.awd

click on "sponza_04" in the library panel

click delete

**Comment by keyemkey** [comment]
partially fixed, but still affected by issue #47
