### ISSUE TITLE
when creating and then deleting a light (point or directional), the representations on stage do not disappear

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#43]
**Steps to reproduce**
- Open PolarBear.awd
- Create a new material on the bear
- Create a new LightPicker on the material
- Create a new PointLight and Directional Light on the lightpicker
- Select the PointLight and click the "delete" button under the list box
- Select the DirectionalLight and click the "delete" button under the list box

**Expected results**

Both lights are removed from the lightpicker and are no longer visible in the view

**Actual results**

Both lights are removed from the lightpicker but remain visible in the view

**Comment by Greg209** [comment]
Although the bug exists, the problem described are not exactly correct. 

**Steps to reproduce**
Add a light to the scene.
Delete the light

**Expected results**
The light is deleted from the library and removed from the view

**Actual results**
The light is removed from the library but remains in the view
