### ISSUE TITLE
Extra tags for meshes & containers don't get saved in an awd

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#82]
**Steps to reproduce**
- Open Monsterhead.awd
- Select mesh
- open extras panel
- create a few name / value pairs
- Click File -> Save As
- Save as monsterheadtag.awd
- Open monsterheadtag.awd
- click on mesh
- open extras panel

**Expected result**

Your name / value pairs are present

**Actual result**

Your name / value pairs are absent

**Comment by 80prozent** [comment]
the user-vars on mesh and container, now get saved as value/name pairs. 
value can be String / Number / Int / Boolean.
