### ISSUE TITLE
Lights don't display in view or library when loading an awd that contains lights

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#84]
**Steps to reproduce**
- Open MonsterHead.awd

**Expected result**

Directional light gizmo should be visible in the view and light should be visible in the library panel

**Actual result**

Directional light gizmo is not present in the view and light is not visible in the library panel (although it can be accessed via the lightpicker)

**Comment by 80prozent** [comment]
Lights are getting imported into the library-panel now.
Gizmo is still not shown.

LightPickers reopens with correct Names in Library-panel now too.

**Comment by rob-bateman** [comment]
Thx Robin, that just leaves the gizmo not appearing now. Greg, could you take a look please?
