### ISSUE TITLE
Saving an unattached light in a file causes the file to hang when reloading

### ISSUE THREAD

**Issue by rob-bateman** [awaytools/AwayBuilder#85]
**Steps to reproduce**
- Open a new file
- Create new directional light with the light library panel (+) button
- Create new point light with the light library panel (+) button
- Save file
- reopen file

**Expected result**

Lights are reloaded into the scene

**Actual result**

Scene never finishes reloading

**Comment by 80prozent** [comment]
RessourceComplete never gets fired, so Scene never finish loading.
The same is true for importing Image-FIles.

I think the fix has to be made in ParserBase.as and i will look into that.

**Comment by 80prozent** [comment]
ok i was wrong. 
RessourceComplete gets fired as it should, but atm AwayBuilder will only remove the BusyCursor when importing files that are containing SceneObjects.

**Comment by 80prozent** [comment]
The Issue seams to have been fixed by one of the latest update.
Importing a Awd-File that contains only one light-object works as expected.
Same is true for Image-Files.
